name: Publish Python Package

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  # Run on latest Ubuntu
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v2  # Check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set the Python version

    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Configure Poetry
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}  # Configure PyPI token

    - name: Build and publish
      run: |
        poetry build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1